# Generated by Django 5.0.5 on 2024-09-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_bi', models.CharField(max_length=22, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('ensino', models.CharField(choices=[('EM', 'Ensino Médio'), ('LC', 'Licenciatura'), ('ME', 'Mestrado'), ('PG', 'Pós-Graduação'), ('DO', 'Doutoramento')], max_length=2)),
                ('estado', models.CharField(choices=[('ESPERA', 'Em Espera'), ('ENCAMINHADO', 'Encaminhado')], default='ESPERA', max_length=12)),
                ('bi_identidade', models.FileField(blank=True, null=True, upload_to='documentos/bi/')),
                ('certificado_medio', models.FileField(blank=True, null=True, upload_to='documentos/certificados/medio/')),
                ('certificado_diploma', models.FileField(blank=True, null=True, upload_to='documentos/certificados/diploma/')),
                ('certificado_best', models.FileField(blank=True, null=True, upload_to='documentos/certificados/best/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='documentos/cv/')),
                ('foto_passe', models.ImageField(blank=True, null=True, upload_to='documentos/foto_passe/')),
                ('cedula_maritima', models.FileField(blank=True, null=True, upload_to='documentos/cedula_maritima/')),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
